### ISSUE TITLE
debug with local Jekyll install

### ISSUE THREAD

**Issue by erwanp** [radis/radis.github.io#1]
The website builds at https://radis.github.io/radis-radiation/ , but theme does not render properly  (expected result: [template of EinsteinPy](https://einsteinpy.org/) ) 

Someone who has Jekyll installed locally would be very helpful to debug it !

**Comment by erwanp** [comment]
@ritzvik would you know someone with experience in Jekyll?

**Comment by ritzvik** [comment]
> @ritzvik would you know someone with experience in Jekyll?

I know one or two guys. Let me ask them if they are up for it. Then I’ll get back to you.

**Comment by ritzvik** [comment]
@shreyasbapat is up for it. 
Hope it helps!

**Comment by shreyasbapat** [comment]
I will do it in some time

**Comment by shreyasbapat** [comment]
@erwanp What do you expect this to look like? And what do you want on teh websote to appear?

**Comment by erwanp** [comment]
Amazing, thank you! I expected a similar layout as in your https://einsteinpy.org/ page, with background image, centered Documentation button, and list of features. Content is there but I have some rendering problems

**Comment by erwanp** [comment]
@shreyasbapat did you have the chance to look at it eventually?

**Comment by shreyasbapat** [comment]
I am out on a vacation. Tomorrow is the last day. I will look into it and
fix it day after tomorrow.
Sorry about that

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by erwanp** [comment]
Changing the project name from radis-radiation to radis.github.io helped. Now the website renders. It's quite dirty (https://radis.github.io/) but it works!

**Comment by erwanp** [comment]
Website updated, I'm closing!
