### ISSUE TITLE
replace GitHub with link to Example Gallery

### ISSUE THREAD

**Issue by erwanp** [radis/radis.github.io#3]
replace GitHub with link to [Example Gallery](https://radis.readthedocs.io/en/latest/auto_examples/index.html) in the topbar of the main website  https://radis.github.io/

@minouHub do you think that would be enough ? 

We coud also add it elsewhere on the docs.

**Comment by minouHub** [comment]
Could you instead write "Examples here". I bet it would be more efficient.

Le lun. 26 juil. 2021 à 19:22, Erwan Pannier ***@***.***> a
écrit :
